@startuml
title Диаграмма контекста монолитной сиетмы "Тёплый дом" (TO-BE)
top to bottom direction
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' ОПИСАНИЕ ПЕРСОН ==
Person(home_owner, "Владелец дома", "Управляет устройствами, настраивает сценарии, просматривает телеметрию")
Person(support_admin, "Команда поддержки", "Техническая поддержка пользователей")

' ОПИСАНИЕ СИСТЕМЫ ==
System(WarmHouseSystem_v2, "Платформа «Умный дом»", "SaaS платформа для управления умными устройствами")

' ОИСАНИЕ ВНЕШНИХ СИСТЕМ ==
System_Ext(smart_devices, "Умные устройства", "Различне IoT устройства в домах пользователей")
System_Ext(partner_devices, "Устройства партнёров", "Сторонние совместимые IoT устройства")
System_Ext(payment_system, "Платёжная система", "Система обработки подписок и платежей")

' ОПИСАНИЕ ВЗАИМОДЕЙСТВИЯ С ПОЛЬЗОВАТЕЛЯМИ ==
Rel(home_owner, WarmHouseSystem_v2, "Использует веб/мобильное приложение", "HTTPS")
Rel(support_admin, WarmHouseSystem_v2, "Предоставляет техподдержку", "HTTPS")

' ОПИСАНИЕ ВЗАИМОДЕЙСТВИЯ С ВНЕШНИМИ СИСТЕМАМИ ==
Rel(WarmHouseSystem_v2, smart_devices, "Управляет и получает телеметрию", "IoT протоколы")
Rel(WarmHouseSystem_v2, partner_devices, "Интегрируется", "Стандартные протоколы")
Rel(WarmHouseSystem_v2, payment_system, "Обрабатывает платежи", "API")

' ПРИМЕЧАНИЯ ==
note left of WarmHouseSystem_v2 : **Ключевые характеристики:**\n• SaaS модель предоставления услуги\n• Самообслуживание пользователями\n• Поддержка множества устройств
note right of home_owner : **Модель использования:**\n• Самостоятельная установка новых устройств в доме\n• Удалённое управление устройствами\n• Настройка автоматизации на основе показателей устройств\n• Оплата подписки сервиса
@enduml